// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Poem } from "./Poem";
import type { Publication } from "./Publication";
import type { Translator } from "./Translator";

export interface Database { createdAt: string, poems: Array<Poem>, translators: Array<Translator>, publications: Array<Publication>, }