// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicationId } from "./PublicationId";

export interface Publication { id: PublicationId, description: string, }