// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranslatorId } from "./TranslatorId";

export interface Translator { id: TranslatorId, name: string, }